"""empty message

Revision ID: 26e1c84f8230
Revises: 4049a789f8eb
Create Date: 2018-08-12 15:24:27.985758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26e1c84f8230'
down_revision = '4049a789f8eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testitems', 'post_description',
               existing_type=sa.VARCHAR(length=2047),
               type_=sa.String(length=511),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testitems', 'post_description',
               existing_type=sa.String(length=511),
               type_=sa.VARCHAR(length=2047),
               existing_nullable=True)
    # ### end Alembic commands ###
