"""empty message

Revision ID: 4049a789f8eb
Revises: 4fcba9a3a118
Create Date: 2018-08-12 14:47:21.069532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4049a789f8eb'
down_revision = '4fcba9a3a118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testitems', 'post_description',
               existing_type=sa.VARCHAR(length=1023),
               type_=sa.String(length=2047),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testitems', 'post_description',
               existing_type=sa.String(length=2047),
               type_=sa.VARCHAR(length=1023),
               existing_nullable=True)
    # ### end Alembic commands ###
