"""empty message

Revision ID: 4fcba9a3a118
Revises: 
Create Date: 2018-07-29 23:30:59.065446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fcba9a3a118'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('listing_name', sa.String(), nullable=False),
    sa.Column('post_link', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('date_scraped', sa.DateTime(), nullable=False),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('listing_dates', sa.JSON(), nullable=True),
    sa.Column('misc', sa.JSON(), nullable=True),
    sa.Column('post_description', sa.String(length=1023), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testitems')
    # ### end Alembic commands ###
