"""empty message

Revision ID: 917e35b2b554
Revises: 26e1c84f8230
Create Date: 2018-08-12 15:25:04.358200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917e35b2b554'
down_revision = '26e1c84f8230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testitems', 'post_description',
               existing_type=sa.VARCHAR(length=511),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testitems', 'post_description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=511),
               existing_nullable=True)
    # ### end Alembic commands ###
