export const GET_DATE = 'GET_DATE'
export type GET_DATE = typeof GET_DATE

export const GET_DATE_SUCCESS = 'GET_DATE_SUCCESS'
export type GET_DATE_SUCCESS = 'GET_DATE_SUCCESS'

export const GET_DATE_FAILURE = 'GET_DATE_FAILURE'
export type GET_DATE_FAILURE = 'GET_DATE_FAILURE'

export const GET_TEST_ITEMS = 'GET_TEST_ITEMS'
export type GET_TEST_ITEMS = typeof GET_TEST_ITEMS

export const GET_TEST_ITEMS_SUCCESS = 'GET_TEST_ITEMS_SUCCESS'
export type GET_TEST_ITEMS_SUCCESS = typeof GET_TEST_ITEMS_SUCCESS

export const GET_TEST_ITEMS_FAILURE = 'GET_TEST_ITEMS_FAILURE'
export type GET_TEST_ITEMS_FAILURE = typeof GET_TEST_ITEMS_FAILURE
